spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_crud
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
