spring:
  application:
    name: "EXERCISE"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_exercise
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql

